"""rename department

Revision ID: 5ae77a4a7cd0
Revises: 163c0fe2ba4c
Create Date: 2024-06-28 15:06:34.888940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae77a4a7cd0'
down_revision = '163c0fe2ba4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
